name: Deploy Hugo site to branch
env:
  LANG: "en_US"
  
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set locale
        run: |
            sudo apt clean
            sudo apt update
            sudo apt install -y locales
            sudo locale-gen en_US
            sudo update-locale LANG=en_US

      - name: Date 1
        run: |
            date

      - name: Set Timezone
        run: |
            sudo ln -sf /usr/share/zoneinfo/America/Denver /etc/localtime
            sudo dpkg-reconfigure -f noninteractive tzdata

      - name: Date 2
        run: |
            date

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
        
      - name: Deploy to branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_branch: deploy

      - name: Bypass Cloudflare for GitHub Action
        uses: https://gitea.katiethe.dev/KatieTheDev/bypass-cloudflare-for-github-action.git@1.2.4
        with:
          cf_zone_id: ${{ secrets.CF_ZONE_ID }}
          cf_api_key: ${{ secrets.CF_API_KEY }}
          
      - name: Trigger Webhook
        run: |
          curl -X POST "${{ secrets.WEBHOOK_URL }}" \
            -H "Authorization: ${{ secrets.WEBHOOK_TOKEN }}" \
            -w "HTTP Status: %{http_code}\n"